### ISSUE TITLE
Link to swagger documentation is broken

### ISSUE THREAD

**Issue by agbeltran** [EBI-Metabolights/MtblsWS-Py#1]
Hi, the link to the swagger documentation in the [README](https://github.com/EBI-Metabolights/MtblsWS-Py/blob/master/README.md) file points to http://www.ebi.ac.uk:5000/mtbls/ws/api/spec.html that is down.

**Comment by jrmacias** [comment]
Hi Alejandra,

Well spotted. This is basically a placeholder by now. Also, with the change from http to https domains at EBI, the final address is still not decided. At the moment this is only accessible from inside the EBI. We are working in a proxy that would allow public access to the API.

Sorry for the inconveniences.

**Comment by agbeltran** [comment]
ok, thank you José Ramón

**Comment by jrmacias** [comment]
I have changed the reference in the README file to make this less confusing. The Swagger API documentation can be accessed once the local instance of the WS is up and running.

**Comment by agbeltran** [comment]
Thank you @jrmacias !
